spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      #    url: jdbc:mysql://192.168.198.129:3306/demo?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    url: jdbc:p6spy:mysql://192.168.198.129:3306/sell?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-enums-package: com.imooc.sell.enums